### ISSUE TITLE
Bump threejs or move to ES modules

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#841]
I saw following message in a build logs:

```
PASS src/ThreeEditor/util/Materials/SimulationMaterial.test.ts
  ● Console

    console.warn
      Scripts "build/three.js" and "build/three.min.js" are deprecated with r150+, and will be removed with r160. Please use ES Modules or alternatives: https://threejs.org/docs/index.html#manual/en/introduction/Installation

    > 1 | import * as THREE from 'three';
        | ^
      2 | import { Editor } from '../../js/Editor';
      3 | import { DEFAULT_MATERIAL_DENSITY, DEFAULT_MATERIAL_ICRU, DEFAULT_MATERIAL_NAME } from './materials';
      4 |

      at Object.<anonymous> (node_modules/three/build/three.js:1:91)
      at Object.<anonymous> (src/ThreeEditor/util/Materials/SimulationMaterial.ts:1:1)
      at Object.<anonymous> (src/ThreeEditor/util/Materials/SimulationMaterial.test.ts:3:1)

PASS src/util/convertUnits/Units.test.ts
PASS src/ThreeEditor/util/CSG/CounterMap.test.ts
PASS src/util/Sort.test.ts
PASS src/ThreeEditor/util/Name.test.ts
PASS src/util/csv/Csv.test.ts
PASS src/App.test.tsx
```

**Comment by grzanka** [comment]
Seems fixed in https://github.com/yaptide/ui/pull/1525
